
@echo off

REM !!! Generated by the fmp-cli 1.80.1.  DO NOT EDIT!

md Analytics\Assets\3rd\fmp-xtc-analytics

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-analytics-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\Analytics\Assets\3rd\fmp-xtc-analytics\
