
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.80.1.  DO NOT EDIT!
//*************************************************************************************

using System.Net;
using Grpc.Core;
using System.Threading.Tasks;
using XTC.FMP.MOD.Analytics.LIB.Proto;

namespace XTC.FMP.MOD.Analytics.App.Service
{
    /// <summary>
    /// Tracker基类
    /// </summary>
    public class TrackerServiceBase : LIB.Proto.Tracker.TrackerBase
    {
    

        public override async Task<BlankResponse> Record(TrackerRecordRequest _request, ServerCallContext _context)
        {
            try
            {
                return await safeRecord(_request, _context);
            }
            catch (ArgumentRequiredException ex)
            {
                return await Task.Run(() => new BlankResponse
                {
                    Status = new LIB.Proto.Status() { Code = -HttpStatusCode.BadRequest.GetHashCode(), Message = ex.Message },
                });
            }
            catch (Exception ex)
            {
                return await Task.Run(() => new BlankResponse
                {
                    Status = new LIB.Proto.Status() { Code = -HttpStatusCode.InternalServerError.GetHashCode(), Message = ex.Message },
                });
            }
        }



        protected virtual async Task<BlankResponse> safeRecord(TrackerRecordRequest _request, ServerCallContext _context)
        {
            return await Task.Run(() => new BlankResponse {
                    Status = new LIB.Proto.Status() { Code = -1, Message = "Not Implemented" },
            });
        }

    }
}

