
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.80.1.  DO NOT EDIT!
//*************************************************************************************

using System.Threading;
using System.Threading.Tasks;
using XTC.FMP.LIB.MVCS;
using XTC.FMP.MOD.Analytics.LIB.Bridge;

namespace XTC.FMP.MOD.Analytics.LIB.MVCS
{
    /// <summary>
    /// Tracker的视图桥接层基类（协议部分）
    /// 处理UI的事件
    /// </summary>
    public class TrackerViewBridgeBase : ITrackerViewBridge
    {

        /// <summary>
        /// 直系服务层
        /// </summary>
        public TrackerService? service { get; set; }


        /// <summary>
        /// 处理Record的提交
        /// </summary>
        /// <param name="_dto">TrackerRecordRequest的数据传输对象</param>
        /// <returns>错误</returns>
        public virtual async Task<Error> OnRecordSubmit(IDTO _dto, object? _context)
        {
            TrackerRecordRequestDTO? dto = _dto as TrackerRecordRequestDTO;
            if(null == service)
            {
                return Error.NewNullErr("service is null");
            }
            return await service.CallRecord(dto?.Value, _context);
        }


    }
}
